name: run unit tests of feature branches

on:
  push:
    branches:
      'features/*'
jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: run unit test
        run: mvn test
